version: '3.5'

networks:
  app-network:
    driver: bridge

services:

#### NODE
  node:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    depends_on:
      - postgresql
    networks:
      - app-network

##### NGINX
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/nginx/ssl
      - ./nginx/auth/:/etc/nginx
    depends_on:
      - app
    networks:
      - app-network

### POSTGRESQL
  postgresql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=montra
      - POSTGRES_USER=montra
      - POSTGRES_PASSWORD=7ZG2dJ54tRQE
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../montra-backend.data/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

#### PG ADMIN
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#    ports:
#      - '5050:80'
#    depends_on:
#      - postgresql
#    networks:
#      - app-network