version: '3.5'

networks:
  app-network:
    driver: bridge

services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=postgres
#    container_name: postgres
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'

#### NODE
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - app-network

##### NGINX
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    container_name: nest-pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#    ports:
#      - '5050:80'
#    depends_on:
#      - db